language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev  -t spasroach/docker-react . 
script:
  - docker run -e CI=true spasroach/docker-react npm run test    

